services:
  container:
    build:
      context: ./ # Use the current directory as the build context
      dockerfile: Dockerfile
    hostname: debian
    container_name: ${CONTAINER_NAME} # defined in .env file
    volumes:
      - ./:/home/user/workspace
      - ${HOME}/.gitconfig:/home/user/.gitconfig
      - ${HOME}/.ssh:/home/user/.ssh
      - ${HOME}/.zsh_history:/home/user/.zsh_history
      - ${HOME}/.kattisrc:/home/user/.kattisrc
    cap_add:
      - ALL
    privileged: true # Grant full privileges to the container
    ports:
      - 8888:8888
    command:
      [
        "bash",
        "-c",
        "sudo chown user:root --recursive /home/user/ && zsh && tail -f /dev/null",
      ]

networks:
  default:
    driver: bridge
