@startuml SequenceDiagram
scale 2
title "UML Sequence Diagram"
actor User

User -> Solution: call static main to create singleton
Solution -> User: prompts data from stdin
User -> Solution: types data in correct format
Solution -> Temperature : creates list of temperature
Solution -> Temperature: gets individual answer
Temperature -> Solution: returns individual answer
Solution -> User: prints formatted final result
@enduml