@startuml Temperature
scale 2
title "UML Class Diagram"

class Temperature {
    .. Instance Variables ..
    - _temp: int
    - _unit: str
    + temp: int {get; set;}
    + unit: str {get; set;}
    .. Overloaded Methods ..
    + __init__(side1: float, side2: float, side3: float): None
    + __str__(): str
    + __repr__(): str
    + __lt__(other: Temperature): bool
    + __gt__(other: Temperature): bool
    + __eq__(other: object): bool
    + __le__(other: Temperature): bool
    + __ge__(other: Temperature): bool
    .. Instance Methods ..
    + is_negative(): bool
}
@enduml