@startuml Temperature
scale 2
title "UML Class Diagram"

class Temperature {
    .. Instance Variables ..
    - _temp: int
    - _unit: str
    - attribute: float
    + temp: int {get; set;}
    + unit: str {get; set;}
    .. Overloaded Methods ..
    - __init__(float, float, float): None
    - __str__(): str
    - __repr__(): str
    - __lt__(Temperature): bool
    - __gt__(Temperature): bool
    - __eq__(Temperature): bool
    - __le__(Temperature): bool
    - __ge__(Temperature): bool
    .. Instance Methods ..
    + is_negative(): bool
}
@enduml